# Generated by Django 5.2.3 on 2025-07-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='order',
            new_name='sort_order',
        ),
    ]
