# Generated by Django 5.2.3 on 2025-07-01 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mainmenuleaf_options_alter_mainmenusub_options_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products_products',
        ),
    ]
