# Generated by Django 5.2.3 on 2025-07-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_order_productcategory_sort_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtertype',
            old_name='order',
            new_name='sort_order',
        ),
        migrations.RenameField(
            model_name='filtervalue',
            old_name='order',
            new_name='sort_order',
        ),
    ]
