# Generated by Django 5.2.3 on 2025-07-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_order_filtertype_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter_values',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.filtervalue'),
        ),
    ]
