# Generated by Django 5.2.3 on 2025-06-25 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'main_category',
            },
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'main_menu',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MainPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'main_panel',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MainMenuSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='main.mainmenu')),
            ],
            options={
                'db_table': 'main_menu_sub',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='MainMenuLeaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='main.mainmenusub')),
            ],
            options={
                'db_table': 'main_menu_leaf',
                'ordering': ['seq'],
            },
        ),
    ]
