# Generated by Django 5.2.3 on 2025-07-01 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenuleaf',
            options={'ordering': ['seq', 'id']},
        ),
        migrations.AlterModelOptions(
            name='mainmenusub',
            options={'ordering': ['seq', 'id']},
        ),
        migrations.AlterField(
            model_name='mainmenuleaf',
            name='sub',
            field=models.ForeignKey(db_column='sub_id', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='main.mainmenusub'),
        ),
        migrations.AlterField(
            model_name='mainmenusub',
            name='menu',
            field=models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='main.mainmenu'),
        ),
    ]
