# Generated by Django 5.2.3 on 2025-07-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='order',
            new_name='sort_order',
        ),
    ]
