# Generated by Django 5.2.3 on 2025-06-30 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold_out', 'Sold Out')], default='active', max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.mainmenu')),
                ('main_menu_leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.mainmenuleaf')),
                ('main_menu_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.mainmenusub')),
            ],
            options={
                'db_table': 'product_product',
                'ordering': ['id'],
            },
        ),
    ]
